language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
branches:
  only:
  - master
install:
  - npm install
script:
  - npm run build
  - export NODE_ENV=production && node_modules/mocha/bin/_mocha --ui exports --colors 'test/**/*.js'
  - npm test
after_success:
  - npm run coverage